default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: mis21helloworld
  username: mis21user
  password: mis21password
  pool: 5
  schema_search_path: public

development:
  <<: *default

production:
  <<: *default